version: '2'

networks:
  chainpoint-node:
    driver: bridge

services:

  postgres:
    restart: always
    image: postgres:9.6.5-alpine
    container_name: postgres-node
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: chainpoint
      POSTGRES_PASSWORD: chainpoint
    networks:
      - chainpoint-node

  redis:
    restart: always
    image: redis:4.0.1-alpine
    container_name: redis-node
    volumes:
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./.data/redis:/data
    networks:
      - chainpoint-node
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  chainpoint-node:
    container_name: chainpoint-node
    image: quay.io/chainpoint/chainpoint-node:${DOCKER_TAG}
    volumes:
      - ~/.chainpoint:/home/node/app/.chainpoint
    build: .
    ports:
      - "${CHAINPOINT_NODE_PORT}:8080"
    networks:
      - chainpoint-node
    depends_on:
      - redis
      - postgres
    environment:
      NODE_TNT_ADDRESS: ${NODE_TNT_ADDRESS}
      CHAINPOINT_NODE_PUBLIC_SCHEME: ${CHAINPOINT_NODE_PUBLIC_SCHEME}
      CHAINPOINT_NODE_PUBLIC_ADDR: ${CHAINPOINT_NODE_PUBLIC_ADDR}
      CHAINPOINT_NODE_PORT: ${CHAINPOINT_NODE_PORT}
