version: '2.1'

networks:
  chainpoint-node:
    driver: bridge

services:

  postgres:
    restart: always
    image: postgres:9.6.5-alpine
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: chainpoint
      POSTGRES_PASSWORD: chainpoint
    networks:
      - chainpoint-node

  redis:
    restart: always
    image: redis:4.0.1-alpine
    volumes:
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./.data/redis:/data
    networks:
      - chainpoint-node
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  chainpoint-node:
    image: quay.io/chainpoint/chainpoint-node:latest
    restart: on-failure
    volumes:
      - ~/.chainpoint:/home/node/app/.chainpoint
    build: .
    ports:
      - "9090:8080"
    networks:
      - chainpoint-node
    depends_on:
      - redis
      - postgres
    environment:
      NODE_TNT_ADDRESS: ${NODE_TNT_ADDRESS}
      CHAINPOINT_NODE_PUBLIC_URI: "${CHAINPOINT_NODE_PUBLIC_URI:-http://0.0.0.0}"
